### ISSUE TITLE
Where can I download the model file 'Cleaned w2V. PKL '?

### ISSUE THREAD

**Issue by QiuSYang** [sagark1729/Automatic-Question-Generation-using-L-LDA-and-NLP-Techniques#1]
`w2v = pickle.load(open('Cleaned_W2V.pkl','rb'))`
Dear author, may I ask where I can download the Word 2 Vector model?

**Comment by sagark1729** [comment]
Hello QiuSYang. https://github.com/mmihaltz/word2vec-GoogleNews-vectors is a large word2vec model. Cleaned_W2V.pkl a subset of this model and saved it in the dictionary format of python. I have removed the symbols, alphanumeric, non-English words from the 3million words available in the GoogleNews Model.

**Comment by QiuSYang** [comment]
> Hello QiuSYang. https://github.com/mmihaltz/word2vec-GoogleNews-vectors is a large word2vec model. Cleaned_W2V.pkl a subset of this model and saved it in the dictionary format of python. I have removed the symbols, alphanumeric, non-English words from the 3million words available in the GoogleNews Model.

Thank you, I have understood.
